controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_drive_controller:
      type: omni_drive_controller/OmniDriveController
      wheel_names: ["rightwheel", "leftwheel", "frontwheel"]
      publish_rate: 50
      velocity_command_topic: "/cmd_vel"
      linear_x_scaling_factor: 1.0
      linear_y_scaling_factor: 1.0
      angular_z_scaling_factor: 1.0
